services:
  postgres:
    image: "postgres:15.4"
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  redis:
    image: redis:7
    ports:
      - 6379:6379
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
